### ISSUE TITLE
Mac build

### ISSUE THREAD

**Issue by Oak-Trees** [DeekyJay/SoundwaveInteractive-releases#1]
Is there a Mac OS X build available somewhere? A .app version would be awesome.

Did or can anyone make a build? That would be amazing!

**Comment by DeekyJay** [comment]
Hey! I should have a Mac build soon. I will keep you posted here. Should be within the next few days!

**Comment by DeekyJay** [comment]
There is a new release out now with a Mac build! Enjoy!
