### ISSUE TITLE
Waiting For Authorization Continuously Appears

### ISSUE THREAD

**Issue by itslumen** [DeekyJay/SoundwaveInteractive-releases#11]
I'm on a Macbook Pro, running the .dmg version, just downloaded it three times. I'm not sure why, but it was connected before it just wouldn't update the soundboard. Now it won't get past the "Waiting For Authorization" screen.

**Comment by DeekyJay** [comment]
Hey! This is something on Mixer's end. They are looking into this currently!

**Comment by DeekyJay** [comment]
This issue has been resolved!
