### ISSUE TITLE
Cannot Authenticate - Microsoft SSO - 0.9.10

### ISSUE THREAD

**Issue by Kirschie** [DeekyJay/SoundwaveInteractive-releases#2]
When launching Soundwave.Interactive.Setup.0.9.10.exe I am asked to authenticate. When I choose 'Microsoft' a new window is launched for third party SSO. However that window remains white and does not timeout. I do not get prompted by my Microsoft authenticator to allow the session. I can only assume it is attempting to connect with Microsoft to get my profile and authenticate me. The third party SSO works on the native Beam.pro site so I know its not my account.

![soundwave](https://cloud.githubusercontent.com/assets/25411412/22558657/7baede5c-e93c-11e6-89d2-37909de1f43a.JPG)

**Comment by DeekyJay** [comment]
Hi @KirscheBuster Thanks for reporting this issue! Beam recently updated their Oauth so I am working on an update to resolve this blank window happening on the external logins, in the mean time, you can connect via Beam credentials.

**Comment by Kirschie** [comment]
@DeekyJay thanks! I just started streaming on Beam but I can only authenticate with MS credentials. I don't have a local Beam account. I will wait for the update. Thank you for the update and quick response. Cheers!

**Comment by spitfire1337** [comment]
@KirscheBuster Even if your authenticated with MS, you can go to your account settings on beam and set a password, you'll then be able to log into soundboard using your MS email and password you set on beam

**Comment by DeekyJay** [comment]
This has been resolved and will be in the next update. 👍

**Comment by Kirschie** [comment]
Thank you @DeekyJay ! Do you know when the next release will be? Again thank you for the work on this project.

**Comment by DeekyJay** [comment]
@KirscheBuster The build with this fix is available here: https://github.com/DeekyJay/SoundwaveInteractive/releases/tag/0.9.12

Note that this is an alpha release.

The update will most likely go live sometime this week.

**Comment by Kirschie** [comment]
@DeekyJay thank you sir.  Thank you for your work I understand the time and effort <3
