### ISSUE TITLE
Logging into the application

### ISSUE THREAD

**Issue by Viphy** [DeekyJay/SoundwaveInteractive-releases#3]
I've tried to log in through Twitter and an account on beam.pro and I can't seem to log in to Soundwave in any way shape or form. I'm trying to use the application, and I've redownloaded a handful of times and it just isn't working.

**Comment by DeekyJay** [comment]
Hi @Viphy, are you using 0.9.12? Try clearing out your AppData\Local\Soundwave Interactive folder.
