### ISSUE TITLE
Authenticate screen disappears and cannot accept it.

### ISSUE THREAD

**Issue by LexusSpeed03** [DeekyJay/SoundwaveInteractive-releases#4]
Can't grant permissions screen closes to fast any thoughts?

**Comment by DeekyJay** [comment]
Hi Dereck,

Please verify that your firewall is not blocking the page from loading by following the guide at http://soundwave.deek.io/wiki

I checked on my end, and have no issues.

Thanks!

**Comment by LexusSpeed03** [comment]
@DeekyJay I have added the rules and still no go. The issue is that when you enter sign in info it loads the approve deny page for about 2-3 seconds and closes the window before I can hit accept. However if I got into beam account says the app is approved on Oauth. Once that screen disappears it says logged in at the top but cannot connect.

**Comment by DeekyJay** [comment]
Have you restarted the application since adding the rules?

**Comment by LexusSpeed03** [comment]
Yes I have restarted it. Also went into Oauth and cleared it and the window doesn't just disappear now but it still failed to connect to beam. I logged out yesterday because sound board wasn't refreshing. And then all this started.

**Comment by DeekyJay** [comment]
What version of the application are you running?

**Comment by LexusSpeed03** [comment]
0.9.12 I have also renamed the appdata roaming to get it to recreate and same thing.

**Comment by LexusSpeed03** [comment]
@DeekyJay Thank you for your help. Believe it or not I had to got to the top of my page and select three dots and select go interactive then hit connect. This is what changed since the mixer update.
