### ISSUE TITLE
Installing Soundwave Interactive..?

### ISSUE THREAD

**Issue by socialgamer** [DeekyJay/SoundwaveInteractive-releases#7]
I've downloaded the .exe file for Windows but every time I launch the App it shows that it's installing. again and again? Did I do something wrong, or am I just able to find the installed location of the App?
Any help will be appreciated. 

All of my settings and files stay intact even after installing every time. So I'm not losing and of my custom buttons? Also, even though the SWI App seems to be error free and even connects just fine to my mixer account, it's not loading up on Mixer (or all of the time) normally.

**Comment by DeekyJay** [comment]
The exe is an installer, it installs and it will be in your start menu to run.

The connection issue has been resolved with the latest version.
