### ISSUE TITLE
interactive board not showing my sound buttons. 

### ISSUE THREAD

**Issue by namelesssaint** [DeekyJay/SoundwaveInteractive-releases#9]
Hi, I have been using soundwave for a month or so and i love it. I had no clue what i was doing with it but i used this video which helped me out a lot. 

https://www.youtube.com/watch?v=xoxuHGAXVA8

Could you tell me if this video is still correct on how to use soundwave.I was streaming and using my sound board on Saturday it worked great,I tried on Sunday and it no longer works and when I click the sound profile I have been using nothing shows up in the Interactive board, but the sounds off to the left that I used in profile are still checked off. what is causing this? If you could take a look at the video and let me know if this is how you still set a sound board up i would greatly appreciate it. 

Below is what my board looks like, i have no boxes in the right section.

![image](https://cloud.githubusercontent.com/assets/29210426/26798812/6de14382-4a08-11e7-87a8-e9a7de6a090a.png)

**Comment by DeekyJay** [comment]
@namelesssaint There must have been a glitch with the conversion. You'll need to go to https://mixer.com/i/studio , find the Soundwave Interactive game, delete it, then restart the app.

**Comment by namelesssaint** [comment]
I did what you said,I went to https://mixer.com/i/studio and deleted the only thing that I could. I logged out of the soundwave app logged back in and it still looks like the screen shot above.
Do I have to create my stuff in the Mixer studio? if so I have no clue how to do that lol.

I made this one up to try to make a new one and still the same, no blocks and it does nothing when I move my sounds from the left to the right.

![image](https://cloud.githubusercontent.com/assets/29210426/26800616/5630a284-4a10-11e7-92d5-b9d01cefb380.png)

**Comment by namelesssaint** [comment]
Ok after I shutdown soundwave 4 times it is now showing my board, it is very strange the 3rd time it showed my board with buttons but nothing in them/no names and I couldn't add anything, 4th time my board was back to normal.

**Comment by DeekyJay** [comment]
That is very odd. I will look into this and see what the cause is.

**Comment by josurr** [comment]
I am having the opposite problem, the Soundwave app shows the 16 buttons but the Control Editor shows nothing:

![upcrhqo](https://user-images.githubusercontent.com/14187881/28006970-7605b534-6506-11e7-954f-40cb14f5309d.png)

Also, is there a way to get more than 16 buttons? I've seen some other streamers with more, but I can't figure out how to get more.

Thanks for the awesome app!

**Comment by DeekyJay** [comment]
You are in the Dev Lab; you must go to the Interactive Studio :) https://mixer.com/i/studio

**Comment by josurr** [comment]
D'oh!

I figured it was something simple... Thanks!
